#!/usr/bin/env bash
# Run the kreuzberg-migration oracle differential end to end.
#
# Captures lilbee's extraction + chunking over a deterministic corpus in the
# pre-migration build (the oracle, kreuzberg 4.x) and the current build
# (kreuzberg 5.x), then compares the two against the QA-matrix invariants.
#
# Usage: tools/qa/oracle/run.sh [oracle_ref]
#   oracle_ref defaults to the merge-base of HEAD and main (last pre-migration build).
set -euo pipefail

REPO_HEAD="$(git rev-parse --show-toplevel)"
ORACLE_REF="${1:-$(git merge-base HEAD main)}"
ORACLE_WT="${REPO_HEAD}/.claude/worktrees/oracle-kz4"
CORPUS="${ORACLE_CORPUS:-/tmp/oracle_corpus}"
OUT_DIR="${ORACLE_OUT:-/tmp}"

export LILBEE_ENABLE_OCR=true
export ORACLE_CORPUS_REGENERATE=0   # both sides read the same generated bytes

echo "==> generating shared corpus at HEAD -> ${CORPUS}"
ORACLE_CORPUS_REGENERATE=1 uv run --no-sync python -c \
  "from pathlib import Path; from tools.qa.oracle.corpus import build_corpus; build_corpus(Path('${CORPUS}'), regenerate=True)"

echo "==> candidate capture (HEAD, kreuzberg 5.x)"
LILBEE_DATA="$(mktemp -d)" uv run --no-sync python -m tools.qa.oracle.capture "${CORPUS}" "${OUT_DIR}/candidate_golden.json"

echo "==> oracle worktree @ ${ORACLE_REF}"
if [ ! -d "${ORACLE_WT}" ]; then
  git worktree add --detach "${ORACLE_WT}" "${ORACLE_REF}"
else
  git -C "${ORACLE_WT}" checkout -q --detach "${ORACLE_REF}"
fi
mkdir -p "${ORACLE_WT}/tools/qa/oracle"
cp "${REPO_HEAD}"/tools/qa/oracle/*.py "${ORACLE_WT}/tools/qa/oracle/"
cp "${REPO_HEAD}/tools/qa/__init__.py" "${ORACLE_WT}/tools/qa/" 2>/dev/null || true
touch "${ORACLE_WT}/tools/__init__.py"

echo "==> oracle venv sync (kreuzberg 4.x)"
(cd "${ORACLE_WT}" && uv sync --extra crawler >/dev/null)

echo "==> oracle capture (kreuzberg 4.x)"
(cd "${ORACLE_WT}" && LILBEE_DATA="$(mktemp -d)" uv run --no-sync python -m tools.qa.oracle.capture "${CORPUS}" "${OUT_DIR}/oracle_golden.json")

echo "==> differential"
LILBEE_DATA="$(mktemp -d)" uv run --no-sync python -m tools.qa.oracle.compare \
  "${OUT_DIR}/oracle_golden.json" "${OUT_DIR}/candidate_golden.json"
