"""Recorded real-world corpus pinning ``clean_display_name`` over live HF names.

The fixture is generated by ``scripts/qa/refresh_display_name_corpus.py`` from
the most-downloaded GGUF repos; tests never touch the network. A prettifier
change that alters any recorded label fails here so the drift is reviewed, and
refreshing the corpus surfaces new community naming conventions as diffs.
"""

from __future__ import annotations

import json
from pathlib import Path

from lilbee.catalog.formatting import clean_display_name

_FIXTURE = Path(__file__).parent / "fixtures" / "display_name_corpus.json"


def _corpus() -> list[dict[str, str]]:
    return json.loads(_FIXTURE.read_text(encoding="utf-8"))


def test_corpus_is_populated() -> None:
    assert len(_corpus()) >= 200


def test_display_names_match_recorded_corpus() -> None:
    mismatches = [
        (entry["repo"], clean_display_name(entry["repo"]), entry["display"])
        for entry in _corpus()
        if clean_display_name(entry["repo"]) != entry["display"]
    ]
    assert not mismatches, (
        "clean_display_name drifted from the recorded corpus; if intentional, rerun "
        f"scripts/qa/refresh_display_name_corpus.py and review the diff: {mismatches[:5]}"
    )
